name: range_header
version: 1.0.0
description: Range header parser for Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/range_header
environment:
  sdk: ">=1.19.0"
dependencies:
  charcode: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  test: ^0.12.0